### PR TITLE
fixed research section

### PR DESCRIPTION
**Pull request by smob123**

### CODE REVIEW

**Comment by atherdon** [comment]
for some reasons netlify deploy failed. will check that details right now

**Comment by atherdon** [comment]
this is why deploy failed
```
7:37:15 AM:   Module not found: Error: Cannot resolve 'file' or 'directory' ../components/Sc  ienceTag/ScienceTag2 in /opt/build/repo/src/pages
7:37:15 AM:   resolve file
7:37:15 AM:     /opt/build/repo/src/components/ScienceTag/ScienceTag2 doesn't exist
7:37:15 AM:     /opt/build/repo/src/components/ScienceTag/ScienceTag2.js doesn't exist
7:37:15 AM:     /opt/build/repo/src/components/ScienceTag/ScienceTag2.jsx doesn't exist
7:37:15 AM:   resolve directory
7:37:15 AM:     /opt/build/repo/src/components/ScienceTag/ScienceTag2 doesn't exist (directo  ry default file)
7:37:15 AM:     /opt/build/repo/src/components/ScienceTag/ScienceTag2/package.json doesn't e  xist (directory description file)
7:37:15 AM:   [/opt/build/repo/src/components/ScienceTag/ScienceTag2]
7:37:15 AM:   [/opt/build/repo/src/components/ScienceTag/ScienceTag2.js]
7:37:15 AM:   [/opt/build/repo/src/components/ScienceTag/ScienceTag2.jsx]
```

**Comment by smob123** [comment]
It could be because I removed ScienceTag2, and added its content to SienceTag file

**Comment by atherdon** [comment]
sure, please run the app and remove unnecessary imports from old files. i
think this will solve the problem


On 10-Jun-2018 at 04:56 AM, smob123 wrote:


It could be because I removed ScienceTag2, and added its content to
SienceTag file

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/atherdon/bebe-grocery/pull/62#issuecomment-396020528>,
or mute the thread

**Pull request merged**
